const GAME_CONFIG = {
  START_YEAR: 1,
  START_DAY: 1,
  START_HOUR: 0,
  START_FLOOR: 1,
  START_LEVEL: 0,
  START_EXP: 0,
  START_STAT_POINTS: 8,

  START_HP: 40,
  START_MAX_HP: 40,

  START_STRENGTH: 4,
  START_DEXTERITY: 4,
  START_STAMINA: 4,
  START_INTELLIGENCE: 4,
  START_CHARISMA: 4,
  START_WISDOM: 4,

  START_RACE: "Lost Soul",
  START_TITLE: "Unawakened",
  START_AREA: "Unknown Chamber",
  START_PERSONA: "ADMIN"
};

module.exports = GAME_CONFIG;